### ISSUE TITLE
provide a pkg-config file

### ISSUE THREAD

**Issue by hasufell** [flintlib/flint2#75]
Pkg-config files (foo.pc) are common interfaces to libraries. These are portable across distributions and platforms and standardize accessing your lib via build systems.
In addition, this also solves some trouble when statically linking such libs, since the dependency libs are put in the "Libs.private" variable (or Requires.private if those libs also have .pc files). Since these are generated at build time, the information is reliable (e.g. Libs.private will reflect whether flint was built with or without gc/ntl/blas support).

check http://people.freedesktop.org/~dbn/pkg-config-guide.html

I might be able to send a pull request for this too, but would need to investigate this a little bit more.

**Comment by jscott0** [comment]
>  (as unfortunately, pkg-config is not available everywhere).

@fingolfin This was a reason against pkg-config CUPS used as well, but I wonder where it comes from? [They say](https://www.freedesktop.org/wiki/Software/pkg-config/)
> It does not require anything but a reasonably well working C compiler and a C library, but can use an installed glib if that is present. (A copy of recent glib2 is shipped together with pkg-config versions since 0.27, and this is sufficient for pkg-config to compile and work properly.)

although a long time ago it was just a shell script, and I wonder if this discussion is from then.

> Also, some distros like debian think it's a good idea to add (or hack) pkgconfig files themselves which can and does lead to cross-distro breakage.

@hasufell Debian does this because pkg-config files, or some other mechanism to get the right build flags, is essential to reliable cross-compilation. Build systems like Autotools and Meson use pkg-config to find libraries this way.

I would like a pkg-config file incorporated (GMP recently got one), and although I'm not very familiar with CMake I'll try looking around.

**Comment by hasufell** [comment]
Great, I've been waited 6 years for this moment... day and night I have been wondering whether anyone will hear my prayers. So long I've been trying to contemplate how people build this project and hoped to find a brother in arms. Now finally the day has come! Let's pack up, saddle our horses and move out into the night!

**Comment by dimpase** [comment]
the problem with Flint (and Arb) is that they have home-grown build systems where adding .pc files is more work that with autotools (there is also a cmake config for Flint nowadays, but it's a bit less stable).
In SageMath we bite the bullet and spell out checks in m4, cf. https://github.com/sagemath/sage/blob/develop/build/pkgs/flint/spkg-configure.m4
- but this could have been much less painful with a .pc file.

**Comment by albinahlback** [comment]
Should be completed now.

**Comment by hasufell** [comment]
That was quick! 😄
